apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: smailandstuff
spec:
  build:
    secrets:
      - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "e9583180-ceac-40e3-90c7-fd7c6e39b968"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET